### ISSUE TITLE
Nested Models

### ISSUE THREAD

**Issue by moshie** [novemberfiveco/datocms-plugin-nextjs-sidebar-preview-button#2]
Quick question does this support nested models?

for example if I wanted to preview a page which was nested inside another page would the plugin correctly send you to:

`/page-parent/page-child`

or would it send you to:

`/page-child`

If it's the latter is their any plans to support nested pages in the future?

**Comment by JanStevens** [comment]
Hi, sorry for the late reply. There is no support for nested pages as you don't get that information back from dato.

You can specify the preview url yourself so if you reference the parent page field (assuming the field is called `parent`) in the entity path: `/$parent/$slug` you would create a preview url to `/12321321/page-child`.

In our preview api route we perform the correct translation of those parent ids to slugs by making request to dato and redirecting the user. This seemed the easiest solution.

**Comment by rolandtoth** [comment]
The solution for this would be to pass the record ID to the preview endpoint, so that we could retrieve the parent pages in code and redirect accordingly. We will probably fork this plugin and see if this would work.

**Comment by JanStevens** [comment]
Since DatoCMS released the Web Previews plugin this plugin is deprecated. Using the new Web Previews plugin you receive all information to construct (and make additional calls if needed) the correct preview url with nested models.

https://github.com/datocms/plugins/tree/master/web-previews#readme
https://www.datocms.com/marketplace/plugins/i/datocms-plugin-web-previews
